try linking with musl for removing some deps

diff --git a/Dockerfile-integration b/Dockerfile-integration
--- a/Dockerfile-integration
+++ b/Dockerfile-integration
@@ -3,9 +3,24 @@
 # SPDX-License-Identifier: AGPL-3.0-or-later
 FROM node:lts-bookworm AS builder
 ENV NODE_VERSION=20.18.0
-RUN apt-get update && apt-get install -y curl build-essential debhelper devscripts pkg-config libssl-dev zip git sqlite3
-RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+RUN apt-get update && apt-get install -y curl build-essential debhelper devscripts pkg-config libssl-dev zip git sqlite3 musl-dev musl-tools
+RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y 
+RUN echo $(dpkg --print-architecture)
 RUN mkdir /build
+RUN if [ "$(dpkg --print-architecture)" = "armhf" ]; then \
+       . /root/.cargo/env && rustup target add armv7-unknown-linux-musleabihf; \
+       ln -svf /usr/bin/ar /usr/bin/arm-linux-musleabihf-ar; \
+       echo "armv7-unknown-linux-musleabihf" > /build/_target ; \
+    fi
+RUN if [ "$(dpkg --print-architecture)" = "arm64" ]; then \
+       . /root/.cargo/env && rustup target add aarch64-unknown-linux-musl; \
+       ln -svf /usr/bin/ar /usr/bin/aarch64-linux-musl-ar; \
+       echo "aarch64-unknown-linux-musl" > /build/_target ; \
+    fi
+RUN if [ "$(dpkg --print-architecture)" = "amd64" ]; then \
+       . /root/.cargo/env && rustup target add x86_64-unknown-linux-musl; \
+       echo "x86_64-unknown-linux-musl" > /build/_target ; \
+    fi
 COPY src /build/src
 COPY libs /build/libs
 COPY Cargo.toml /build/Cargo.toml
@@ -18,7 +33,8 @@ RUN echo "INSERT OR IGNORE INTO peer (guid, id, uuid, pk, created_at, 'user', st
 # this workaround is needed because QEMU emulating 32 bits platfom on 64 bits host
 # see https://github.com/rust-lang/cargo/issues/8719
 RUN mv /root/.cargo /tmp && rm -rf /root/.cargo && mkdir -p /root/.cargo 
-RUN --mount=type=tmpfs,target=/root/.cargo mkdir -p /root/.cargo \
+RUN --mount=type=tmpfs,target=/root/.cargo export TARGET=$(cat /build/_target) \
+    && mkdir -p /root/.cargo \
     && cp -av /tmp/.cargo/* /root/.cargo/ && ls -lR /root/.cargo \
     && if [ ! -f /root/.cargo/config.toml ]; then \
         echo "" > /root/.cargo/config.toml; \
@@ -27,11 +43,11 @@ RUN --mount=type=tmpfs,target=/root/.cargo mkdir -p /root/.cargo \
     mv /root/.cargo/config.tmp /root/.cargo/config.toml \
     && . /root/.cargo/env && cd /build \ 
     && cargo update -p sctgdesk-api-server \
-    && DATABASE_URL=sqlite://$(pwd)/db_v2.sqlite3 cargo build --release \
+    && DATABASE_URL=sqlite://$(pwd)/db_v2.sqlite3 cargo build --target=$TARGET --release || (echo "Build failed, entering sleep mode for debugging..." && cp -av /root/.cargo /build/ && exit 1) \
     && mkdir -p /build/ubuntu-jammy/bin \
-    && cp /build/target/release/hbbr /build/ubuntu-jammy/bin/ \
-    && cp /build/target/release/hbbs /build/ubuntu-jammy/bin/ \
-    && cp /build/target/release/rustdesk-utils /build/ubuntu-jammy/bin/
+    && cp /build/target/$(cat /build/_target)/release/hbbr /build/ubuntu-jammy/bin/ \
+    && cp /build/target/$(cat /build/_target)/release/hbbs /build/ubuntu-jammy/bin/ \
+    && cp /build/target/$(cat /build/_target)/release/rustdesk-utils /build/ubuntu-jammy/bin/
 COPY systemd /build/ubuntu-jammy/systemd
 COPY debian /build/ubuntu-jammy/debian
 RUN cd /build/ubuntu-jammy \
@@ -44,7 +60,7 @@ COPY oauth2.toml /build/ubuntu-jammy/bin/oauth2.toml
 FROM ubuntu:jammy
 RUN mkdir -p /usr/local/share/debpackages
 COPY --from=builder /build/*.deb /usr/local/share/debpackages
-COPY --from=builder /build/target/release/hbbs /usr/local/bin/hbbs
+COPY --from=builder /build/ubuntu-jammy/bin/hbbs /usr/local/bin/hbbs
 COPY --from=builder /build/ubuntu-jammy/bin/oauth2.toml /usr/local/bin/oauth2.toml
-COPY --from=builder /build/target/release/hbbr /usr/local/bin/hbbr
-COPY --from=builder /build/target/release/rustdesk-utils /usr/local/bin/rustdesk-utils
+COPY --from=builder /build/ubuntu-jammy/bin/hbbr /usr/local/bin/hbbr
+COPY --from=builder /build/ubuntu-jammy/bin/rustdesk-utils /usr/local/bin/rustdesk-utils
